version: '3.8'

services:
  rediscache:
    image: redis
    container_name: rediscache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      rediscache:
          condition: service_started
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq    
  cleanarchitecturedb:
    image: postgres
    container_name: cleanarchitecturedb
    restart : always
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_PASSWORD=1283"
    depends_on:
      rediscache:
          condition: service_started
      rabbitmq:
          condition: service_started
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  webapi:
    image: webapi
    restart: always
    build:
      context: .
      dockerfile: src/Presentation/WebAPI/Dockerfile
    ports:
      - "5010:80"
    depends_on:
      - cleanarchitecturedb
      - rediscache
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PostgreSqlConnection=User ID=postgres; Password=1283; Server=cleanarchitecturedb; Port=5432;Database=CleanArchitecture;Integrated Security=true;"
      - "ConnectionStrings:SeriLogConnection=User ID=postgres; Password=1283; Server=cleanarchitecturedb; Port=5432;Database=CleanArchitecture;Integrated Security=true;"
      - "CacheSettings:RedisURL=rediscache"
      - "CacheSettings:Port=6379"
      - "CacheSettings:PreferRedis=true"
      - "RabbitMQSettings:HostName=rabbitmq"
      - "RabbitMQSettings:UserName=guest"
      - "RabbitMQSettings:Password=guest"
      - "RabbitMQSettings:VirtualHost=/"
      - "RabbitMQSettings:Port=5672"
    
      
volumes:
  redis_volume:
  postgres_volume:
  rabbitmq_data:
